apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-create-user
  annotations: 
    "helm.sh/hook": post-upgrade # Runs job after upgrading the chart
    "helm.sh/hook-weight": "1" # Runs after migrations
    "helm.sh/hook-delete-policy": hook-succeeded 
spec:
  template:
    spec:
      containers:
        - name: create-user
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          args:
            - "users"
            - "create"
            - "-r"
            - Admin
            - "-u"
            - admin
            - "-e"
            - admin@example.com
            - "-f"
            - admin
            - "-l"
            - user
            - "-p"
            - admin    
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: connection-secret
                  key: connection      
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: fernet-secret
                  key: fernet

          volumeMounts:
            - name: airflow-config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
      volumes:
        - name: airflow-config
          configMap:
            name: base-config

      restartPolicy: OnFailure